### ISSUE TITLE
When can use new version like as Primefaces demo?

### ISSUE THREAD

**Issue by fenglinyushu** [primefaces/primeui#112] opened 2016-01-20 14:14 UTC
I have see there are some new web components such as calendar and other is Primefaces demo.
When we can use it ?
Thanks!

**Comment by cagataycivici** [comment] 2016-01-20 23:27
Which demo are your referring to?

**Comment by fenglinyushu** [comment] 2016-01-22 11:40
The demo at

**Comment by cagataycivici** [comment] 2016-01-24 11:14
Duplicate of #137

**Closed by cagataycivici** 2016-01-24 11:14 UTC
